{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# %pip install opensearch-py pyspark matplotlib scikit-learn seaborn pandas"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "\n",
    "rootpath = os.path.abspath(\"/home/robertc/Git/pfun-cma-model\")\n",
    "if rootpath not in sys.path:\n",
    "    sys.path.insert(0, rootpath)\n",
    "from pfun_cma_model.embed import Embedder"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Run the embedder -> embeddings -> Opensearch domain"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating embeddings...\n",
      "Saving embeddings to OpenSearch...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:opensearch:POST https://10.1.131.236:9200/_bulk [status:N/A request:0.367s]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 714, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 403, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1053, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connection.py\", line 419, in connect\n",
      "    self.sock = ssl_wrap_socket(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 453, in ssl_wrap_socket\n",
      "    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 495, in _ssl_wrap_socket_impl\n",
      "    return ssl_context.wrap_socket(sock)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 513, in wrap_socket\n",
      "    return self.sslsocket_class._create(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1104, in _create\n",
      "    self.do_handshake()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1375, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/opensearchpy/connection/http_urllib3.py\", line 240, in perform_request\n",
      "    response = self.pool.urlopen(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 798, in urlopen\n",
      "    retries = retries.increment(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/retry.py\", line 525, in increment\n",
      "    raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/packages/six.py\", line 769, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 714, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 403, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1053, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connection.py\", line 419, in connect\n",
      "    self.sock = ssl_wrap_socket(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 453, in ssl_wrap_socket\n",
      "    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 495, in _ssl_wrap_socket_impl\n",
      "    return ssl_context.wrap_socket(sock)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 513, in wrap_socket\n",
      "    return self.sslsocket_class._create(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1104, in _create\n",
      "    self.do_handshake()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1375, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)\n",
      "WARNING:opensearch:POST https://10.1.131.236:9200/_bulk [status:N/A request:0.306s]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 714, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 403, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1053, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connection.py\", line 419, in connect\n",
      "    self.sock = ssl_wrap_socket(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 453, in ssl_wrap_socket\n",
      "    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 495, in _ssl_wrap_socket_impl\n",
      "    return ssl_context.wrap_socket(sock)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 513, in wrap_socket\n",
      "    return self.sslsocket_class._create(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1104, in _create\n",
      "    self.do_handshake()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1375, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/opensearchpy/connection/http_urllib3.py\", line 240, in perform_request\n",
      "    response = self.pool.urlopen(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 798, in urlopen\n",
      "    retries = retries.increment(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/retry.py\", line 525, in increment\n",
      "    raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/packages/six.py\", line 769, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 714, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 403, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1053, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connection.py\", line 419, in connect\n",
      "    self.sock = ssl_wrap_socket(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 453, in ssl_wrap_socket\n",
      "    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 495, in _ssl_wrap_socket_impl\n",
      "    return ssl_context.wrap_socket(sock)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 513, in wrap_socket\n",
      "    return self.sslsocket_class._create(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1104, in _create\n",
      "    self.do_handshake()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1375, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)\n",
      "WARNING:opensearch:POST https://10.1.131.236:9200/_bulk [status:N/A request:0.357s]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 714, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 403, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1053, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connection.py\", line 419, in connect\n",
      "    self.sock = ssl_wrap_socket(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 453, in ssl_wrap_socket\n",
      "    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 495, in _ssl_wrap_socket_impl\n",
      "    return ssl_context.wrap_socket(sock)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 513, in wrap_socket\n",
      "    return self.sslsocket_class._create(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1104, in _create\n",
      "    self.do_handshake()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1375, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/opensearchpy/connection/http_urllib3.py\", line 240, in perform_request\n",
      "    response = self.pool.urlopen(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 798, in urlopen\n",
      "    retries = retries.increment(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/retry.py\", line 525, in increment\n",
      "    raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/packages/six.py\", line 769, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 714, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 403, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1053, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connection.py\", line 419, in connect\n",
      "    self.sock = ssl_wrap_socket(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 453, in ssl_wrap_socket\n",
      "    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 495, in _ssl_wrap_socket_impl\n",
      "    return ssl_context.wrap_socket(sock)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 513, in wrap_socket\n",
      "    return self.sslsocket_class._create(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1104, in _create\n",
      "    self.do_handshake()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1375, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)\n",
      "WARNING:opensearch:POST https://10.1.131.236:9200/_bulk [status:N/A request:0.291s]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 714, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 403, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1053, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connection.py\", line 419, in connect\n",
      "    self.sock = ssl_wrap_socket(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 453, in ssl_wrap_socket\n",
      "    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 495, in _ssl_wrap_socket_impl\n",
      "    return ssl_context.wrap_socket(sock)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 513, in wrap_socket\n",
      "    return self.sslsocket_class._create(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1104, in _create\n",
      "    self.do_handshake()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1375, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/opensearchpy/connection/http_urllib3.py\", line 240, in perform_request\n",
      "    response = self.pool.urlopen(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 798, in urlopen\n",
      "    retries = retries.increment(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/retry.py\", line 525, in increment\n",
      "    raise six.reraise(type(error), error, _stacktrace)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/packages/six.py\", line 769, in reraise\n",
      "    raise value.with_traceback(tb)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 714, in urlopen\n",
      "    httplib_response = self._make_request(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 403, in _make_request\n",
      "    self._validate_conn(conn)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 1053, in _validate_conn\n",
      "    conn.connect()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/connection.py\", line 419, in connect\n",
      "    self.sock = ssl_wrap_socket(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 453, in ssl_wrap_socket\n",
      "    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/site-packages/urllib3/util/ssl_.py\", line 495, in _ssl_wrap_socket_impl\n",
      "    return ssl_context.wrap_socket(sock)\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 513, in wrap_socket\n",
      "    return self.sslsocket_class._create(\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1104, in _create\n",
      "    self.do_handshake()\n",
      "  File \"/home/robertc/Git/pfun-cma-model/.conda/lib/python3.10/ssl.py\", line 1375, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)\n"
     ]
    }
   ],
   "source": [
    "defaults = dict(grid_params=dict(num=8, kind=\"random\"),\n",
    "                require_ssh_tunnel=False)\n",
    "kwds = {**defaults}\n",
    "embedder = Embedder(**kwds)\n",
    "embedder.run()  # type: ignore"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Initialize opensearch client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "osearc = embedder.opensearch_client\n",
    "res = osearc.search(\n",
    "    index=\"embeddings\", body={\"size\": 10, \"_source\": \"embedding\"}, scroll=\"2m\"\n",
    ")\n",
    "scroll_id = res[\"_scroll_id\"]\n",
    "scroll_size = res[\"hits\"][\"total\"][\"value\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "res"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Setup spark"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyspark.sql import SparkSession\n",
    "import os\n",
    "\n",
    "# .config(\"spark.jars\", os.path.join(rootpath, \"pfun_cma_model/embed/pyspark_jars/opensearch-spark-30_2.13-1.0.1.jar\"))\n",
    "spark = SparkSession.builder \\\n",
    "    .config(\"spark.cores.max\", \"8\") \\\n",
    "    .config(\"spark.kubernetes.container.image\", \"docker.io/bitnami/spark:3.5.0-debian-11-r0\") \\\n",
    "    .config(\"spark.executor.instances\", \"4\") \\\n",
    ".config(\"spark.jars\", os.path.join(rootpath, \"pfun_cma_model/embed/pyspark_jars/elasticsearch-spark-20_2.11-8.10.2.jar\")) \\\n",
    "    .appName(\"pfun-cma-model-embed\") \\\n",
    "    .getOrCreate()\n",
    "spark.conf.set('spark.sql.shuffle.partitions', int(16 * 2.5))\n",
    "spark.conf.set('spark.default.parallelism', 16)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Get Data from OpenSearch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "embeddings = [(d[\"_source\"][\"embedding\"][0][\"embedding\"],) for d in res[\"hits\"][\"hits\"]]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def getDataFromOSWithSpark(index: str = \"embeddings\", sample_fraction: float | None = 0.1):\n",
    "    #: Get data from opensearch (with spark)\n",
    "    df = (\n",
    "        spark.read.format(\"org.elasticsearch.spark.sql\")\n",
    "        .option(\"es.port\", \"9201\")\n",
    "        .option(\"es.net.ssl\", \"false\")\n",
    "        .option(\"es.nodes\", \"192.168.1.64\")\n",
    "        .load(f\"{index}/float\")\n",
    "    )\n",
    "    if sample_fraction is not None:\n",
    "        # Create random sample of 10% of the data\n",
    "        df_sample = df.sample(False, sample_fraction)\n",
    "        return df_sample\n",
    "    else:\n",
    "        return df\n",
    "\n",
    "\n",
    "# df = getDataFromOSWithSpark(sample_fraction=0.1)\n",
    "# df.persist()\n",
    "# df.show(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyspark.sql.types import ArrayType, DoubleType, StructType, StructField\n",
    "\n",
    "schema = StructType([StructField(\"list_features\", ArrayType(DoubleType()))])\n",
    "df = spark.createDataFrame(embeddings, schema=schema)\n",
    "\n",
    "from pyspark.ml.linalg import Vectors, VectorUDT\n",
    "from pyspark.sql.functions import udf\n",
    "\n",
    "# UDF to convert array into vector\n",
    "vector_udf = udf(lambda l: Vectors.dense(l), VectorUDT())\n",
    "df = df.withColumn(\"features\", vector_udf(\"list_features\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = df.repartition(\"features\")\n",
    "df.persist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyspark.ml.clustering import KMeans\n",
    "\n",
    "kmeans = KMeans(k=8, seed=23)\n",
    "model = kmeans.fit(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "from sklearn.decomposition import PCA\n",
    "import seaborn as sns\n",
    "import pandas as pd\n",
    "\n",
    "pca = PCA(n_components=2)\n",
    "df_pandas = pd.DataFrame(\n",
    "    model.transform(df)\n",
    "    .rdd.map(lambda r: (float(r.features[0]), float(r.features[1]), int(r.prediction)))\n",
    "    .collect(),\n",
    "    columns=[\"x\", \"y\", \"cluster\"],\n",
    ")\n",
    "df_pandas[\"x\"], df_pandas[\"y\"] = zip(*pca.fit_transform(df_pandas[[\"x\", \"y\"]]))\n",
    "plt.rc(\"figure\", figsize=(10, 8))\n",
    "sns.scatterplot(x=\"x\", y=\"y\", hue=\"cluster\", data=df_pandas)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "pca.explained_variance_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_query_vector():\n",
    "    from pfun_cma_model.embed import encode\n",
    "    from pfun_cma_model.runtime.chalicelib.engine.cma_sleepwake import CMASleepWakeModel\n",
    "    cma = CMASleepWakeModel()\n",
    "    raw_text = cma.run().to_json()\n",
    "    queryVector = encode(raw_text)[0].tolist()\n",
    "    return queryVector\n",
    "\n",
    "\n",
    "def get_sample_query_vector():\n",
    "    sample = osearc.search(\n",
    "        index=\"embeddings\", body={\"size\": 1, \"_source\": \"embedding\"}, scroll=\"2m\"\n",
    "    )\n",
    "    queryVector = sample['hits']['hits'][0]['_source']['embedding'][0]['embedding']\n",
    "    return queryVector\n",
    "\n",
    "\n",
    "queryVector = get_sample_query_vector()\n",
    "\n",
    "query = {\n",
    "    \"size\": 1,\n",
    "    \"query\": {\n",
    "        \"script_score\": {\n",
    "            \"query\": {\"match_all\": {}},\n",
    "            \"script\": {\n",
    "                \"source\": \"cosineSimilarity(params.queryVector, doc['embedding']) + 1.0\",\n",
    "                \"params\": {\n",
    "                    \"queryVector\": queryVector\n",
    "                }\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "}\n",
    "\n",
    "response = osearc.search(index=\"embeddings\", body=query, error_trace=True)\n",
    "\n",
    "# Extract hit and score\n",
    "hit = response['hits']['hits'][0]['_source']\n",
    "score = response['hits']['hits'][0]['_score']\n",
    "hit_id = response['hits']['hits'][0]['_id']\n",
    "\n",
    "print(hit_id, hit, score)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
